### ISSUE TITLE
Upgrade to Java 1.8 and Spring 4.x

### ISSUE THREAD

**Issue by rusio** [mazen17/payroll#2]
Shiny new project with Java 1.6?

ни са излагай ;-)

**Comment by mazen17** [comment]
haha smenqi prai kvoto ta kefi

**Comment by rusio** [comment]
Spring MVC ne go razbiram mnogo, ti go oprai :-)

**Comment by mazen17** [comment]
done

**Comment by rusio** [comment]
bravo :-)
